title: Guo Xuan WONG
logo: "/images/ProfilePic.png"
description: > 
  <center><b>UCL BSc Economics'21</b></center>
  <center><b>Columbia MS Business Analytics '22</b></center>
  <br>
  <center>âœ¦</center>
  <br>
  <center>Passionate about leveraging analytics and data science tools to drive decision-making and impact</center>
   
  <br>

  <center><a href="https://www.linkedin.com/in/guoxuan-wong/">LinkedIn</a> | <a href="https://github.com/GuoXuan97">GitHub</a></center>
  
theme: jekyll-theme-minimal
google_analytics: UA-175961645-1
