title: Guo Xuan WONG 
logo: "/images/ProfilePic.jpg"
description: > 
  <center>Final Year Economics undergraduate at University College London</center>
  <br>
  <center>âœ¦</center>
  <br>
  <center>Passionate about leveraging analytics and machine learning to drive decision-making and scale social impact.</center>
  
  <br><br>

  <a href="https://www.linkedin.com/in/guoxuan-wong/">View My LinkedIn Profile</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-175961645-1
