title: Guo Xuan WONG
logo: "/images/ProfilePic.png"
description: > 
  <center><b>Final Year Economics undergraduate at University College London</b></center>
  <br>
  <center>âœ¦</center>
  <br>
  <center>Passionate about leveraging analytics and machine learning to drive decision-making and scale social impact</center>
   
  <br>

  <center><a href="https://www.linkedin.com/in/guoxuan-wong/">LinkedIn</a> | <a href="https://github.com/GuoXuan97">GitHub</a></center>
  
theme: jekyll-theme-minimal
google_analytics: UA-175961645-1

