title: Guo Xuan WONG # your name (or website title) here
logo: "/images/ProfilePic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi there! I am a final year Economics undergraduate at University College London. I am interested in problem solving using machine learning and analytics tools.
  <br><br>
  This page showcases some of the exciting projects that I've worked on!
  <br><br>

  <a href="https://www.linkedin.com/in/guoxuan-wong/">View My LinkedIn Profile</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-175961645-1
