title: Guo Xuan WONG # your name (or website title) here
logo: "/images/ProfilePic.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Final Year Economics undergraduate at University College London
  <br>
  <center>âœ¦</center>
  <br>
  Passionate about leveraging analytics and machine learning to drive decision-making and scale social impact.
  
  <br><br>

  <a href="https://www.linkedin.com/in/guoxuan-wong/">View My LinkedIn Profile</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-175961645-1
